version: '3'

services:
  mysql:
    build: 
      context: ./MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mysql
    build:
      context: ./Wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
volumes:
  mysql_data:
  wp_data: