version: '3'

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=lab3
      - MYSQL_PASSWORD=password

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=lab3
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
volumes:
  mysql_data:
  wp_data: